# -*- coding: utf-8 -*-
"""erro-e-excecoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrQKtpM3U2hN_E48RgdJIa1Apy1N5UsB

Erros e Exceções:
"""

# erro
print('Olá)

# criando uma função:
def numDiv (num1, num2):
  resultado = num1 / num2
  print(resultado)

# Execução sem erro:
numDiv(6,2)

# Execução com erro:
numDiv(2,0)

"""Try, Except e Finally"""

8 + 's'

# Usando try e except
try:
  8 + 's'
except TypeError:
  print('Operação não permitida')

# utilizando try, except e else:
try:
  f = open('/testandoerros.txt', 'w')
  f.write('Gravando no arquivo')
except IOError:
  print('Erro: Arquivo não encontrado ou não pode ser lido.')
else:
  print('Conteúdo gravado com sucesso.')
  f.close()

# utilizando try, except e else:
try:
  f = open('/testandoerros', 'r')
  f.write('Gravando no arquivo')
except IOError:
  print('Erro: Arquivo não encontrado ou não pode ser lido.')
else:
  print('Conteúdo gravado com sucesso.')
  f.close()

# utilizando o Finally:
try:
  f = open('/testandoerros.txt', 'w')
  f.write('Gravando no arquivo.')
except IOError:
  print('Erro: Arquivo não encontrado ou não pode ser salvo')
else:
  print('Conteúdo gravado com sucesso.')
  f.close()
finally:
  print('Comandos do bloco finally sempre são executados.')

def askInt():
  try:
    val = int((input('Digite um número: ')))
  except  UnboundLocalError:
    print('Você não digitou um número!')
  finally:
    print('Obrigado.')
    print(val)

askInt()

def askInt():
    try:
        val = int((input("Digite um número: ")))
    except:
        print ("Você não digitou um número!")
        val = int((input("Tente novamente. Digite um número: ")))
    finally:
        print ("Obrigado!")
    print (val)

askInt()

def askInt():
  while True:
    try:
        val = int(input("Digite um número: "))
    except:
        print ("Você não digitou um número!")
        continue
    else:
        print('Obrigado por digitar um número.')
        break
    finally:
        print ("Fim da execução!")
    print (val)

askInt()

tuple = (1,2,3,4,5)
try:
    tuple.append(6)
    for each in tuple:
        print(each)
except AttributeError as e:
    print('Erro: ', e)
except IOError as e:
    print('Erro de I/O:', e)